---
- name: Converge
  hosts: all
  become: true

  vars:
    # Role: yum_config_manager
    repositories:
      enabled:
        - rhui-REGION-rhel-server-rhscl
        - rhui-REGION-rhel-server-debug-rhscl

    # Ansible Role: NodeJS
    use_scl: true
    nodejs_install_npm_user: root
    npm_config_prefix: /opt/rh/rh-nodejs12/root/usr
    npm_config_unsafe_perm: "true"
    nodejs_npm_global_packages:
      - node-sass
      - name: jslint
        version: 0.12.0
      - name: yo

  roles:
    - role: nycrecords.yum_config_manager
    - role: ansible-role-nodejs